### ISSUE TITLE
感谢作者,关于分享,有个问题?

### ISSUE THREAD

**Issue by waterpotter** [fangx/ZhiHuMVP#4]
比如,分享到微信以后,会出现dialog,dialog下方有两个按钮,一个显示的内容是"返回第三方工具",另一个显示的内容是"留在微信";这个用的貌似是原生的代码逻辑,如何把"返回第三方工具",修改为返回app的名字呢?

**Comment by waterpotter** [comment]
呃...,好尴尬,这个问题和审核有关

**Comment by fangx** [comment]
恩恩~
